global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'ayaztrade-production'
    environment: 'production'

scrape_configs:
  - job_name: 'ayaztrade-backend'
    static_configs:
      - targets: ['backend:5000']
    metrics_path: '/api/v1/metrics'
    scrape_interval: 10s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']
    metrics_path: '/_prometheus/metrics'


