apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ayaztrade-backups-pvc
  namespace: ayaztrade
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
