import * as Joi from 'joi';

export const configValidationSchema = Joi.object({
  // Application Configuration
  NODE_ENV: Joi.string().valid('development', 'production', 'test').default('development'),
  APP_NAME: Joi.string().default('AyazTrade'),
  APP_VERSION: Joi.string().default('1.0.0'),
  APP_URL: Joi.string().uri().required(),
  FRONTEND_URL: Joi.string().uri().required(),
  ADMIN_URL: Joi.string().uri().required(),
  B2B_URL: Joi.string().uri().required(),
  API_PREFIX: Joi.string().default('api/v1'),
  PORT: Joi.number().default(3000),
  HOST: Joi.string().default('0.0.0.0'),

  // Database Configuration - Standardized to DATABASE_*
  DATABASE_URL: Joi.string().required(),
  DATABASE_HOST: Joi.string().default('localhost'),
  DATABASE_PORT: Joi.number().default(5432),
  DATABASE_USER: Joi.string().required(),
  DATABASE_PASSWORD: Joi.string().required(),
  DATABASE_NAME: Joi.string().required(),
  DATABASE_SSL: Joi.string().valid('true', 'false').default('false'),
  DATABASE_LOGGING: Joi.string().valid('true', 'false').default('false'),
  DATABASE_CONNECTION_LIMIT: Joi.number().default(10),
  DATABASE_IDLE_TIMEOUT: Joi.number().default(30000),
  DATABASE_CONNECTION_TIMEOUT: Joi.number().default(10000),
  DATABASE_MIGRATIONS_RUN: Joi.string().valid('true', 'false').default('false'),
  DATABASE_CACHE_DURATION: Joi.number().default(30000),

  // Redis Configuration
  REDIS_HOST: Joi.string().default('localhost'),
  REDIS_PORT: Joi.number().default(6379),
  REDIS_PASSWORD: Joi.string().allow('').default(''),
  REDIS_DB: Joi.number().default(0),
  REDIS_KEY_PREFIX: Joi.string().default('ayaztrade:'),

  // Elasticsearch Configuration
  ELASTICSEARCH_NODE: Joi.string().uri().required(),
  ELASTICSEARCH_USERNAME: Joi.string().allow('').default(''),
  ELASTICSEARCH_PASSWORD: Joi.string().allow('').default(''),
  ELASTICSEARCH_MAX_RETRIES: Joi.number().default(3),
  ELASTICSEARCH_REQUEST_TIMEOUT: Joi.number().default(30000),
  ELASTICSEARCH_PING_TIMEOUT: Joi.number().default(3000),
  ELASTICSEARCH_SNIFF_ON_START: Joi.string().valid('true', 'false').default('false'),
  ELASTICSEARCH_SNIFF_ON_CONNECTION_FAULT: Joi.string().valid('true', 'false').default('true'),
  ELASTICSEARCH_SNIFF_INTERVAL: Joi.number().default(300000),

  // JWT Configuration
  JWT_SECRET: Joi.string().required(),
  JWT_EXPIRES_IN: Joi.string().default('24h'),
  JWT_ISSUER: Joi.string().default('ayaztrade'),
  JWT_AUDIENCE: Joi.string().default('ayaztrade-users'),

  // Security Configuration
  CORS_ORIGIN: Joi.string().default('*'),
  CORS_ENABLED: Joi.string().valid('true', 'false').default('true'),
  CORS_ALLOWED_ORIGINS: Joi.string().default('http://localhost:3000,http://localhost:5001,http://localhost:5002,https://admin.ayaztrade.com,https://ayaztrade.com,https://b2b.ayaztrade.com'),
  RATE_LIMIT_ENABLED: Joi.string().valid('true', 'false').default('true'),
  RATE_LIMIT_WINDOW_MS: Joi.number().default(900000),
  RATE_LIMIT_MAX: Joi.number().default(100),
  THROTTLE_TTL: Joi.number().default(60),
  THROTTLE_LIMIT: Joi.number().default(10),
  BCRYPT_SALT_ROUNDS: Joi.number().default(12),
  SESSION_SECRET: Joi.string().required(),

  // DDoS Protection
  DDOS_MAX_REQUESTS_PER_MINUTE: Joi.number().default(60),
  DDOS_MAX_REQUESTS_PER_HOUR: Joi.number().default(1000),
  DDOS_BLOCK_DURATION_MS: Joi.number().default(900000),
  DDOS_WHITELIST_IPS: Joi.string().allow('').default(''),
  DDOS_BLACKLIST_IPS: Joi.string().allow('').default(''),
  DDOS_ENABLE_AUTO_BLOCK: Joi.string().valid('true', 'false').default('true'),
  DDOS_ENABLE_LOGGING: Joi.string().valid('true', 'false').default('true'),

  // Monitoring Configuration
  PROMETHEUS_ENABLED: Joi.string().valid('true', 'false').default('true'),
  PROMETHEUS_PORT: Joi.number().default(9090),
  PROMETHEUS_PATH: Joi.string().default('/metrics'),
  PROMETHEUS_DEFAULT_METRICS: Joi.string().valid('true', 'false').default('true'),
  PROMETHEUS_TIMEOUT: Joi.number().default(5000),
  PROMETHEUS_PREFIX: Joi.string().default('ayaztrade_'),
  HEALTH_CHECK_ENABLED: Joi.string().valid('true', 'false').default('true'),
  HEALTH_CHECK_PATH: Joi.string().default('/health'),
  HEALTH_CHECK_TIMEOUT: Joi.number().default(5000),
  LOG_LEVEL: Joi.string().valid('error', 'warn', 'log', 'debug', 'verbose').default('info'),
  LOG_FORMAT: Joi.string().valid('json', 'text').default('json'),
  LOG_FILE_ENABLED: Joi.string().valid('true', 'false').default('true'),
  LOG_FILE_PATH: Joi.string().default('./logs'),
  LOG_FILE_MAX_SIZE: Joi.string().default('10m'),
  LOG_FILE_MAX_FILES: Joi.number().default(5),
  TRACING_ENABLED: Joi.string().valid('true', 'false').default('true'),
  TRACING_SERVICE_NAME: Joi.string().default('ayaztrade'),

  // Firebase (Push Notifications)
  FIREBASE_PROJECT_ID: Joi.string().allow('').default(''),
  FIREBASE_PRIVATE_KEY_ID: Joi.string().allow('').default(''),
  FIREBASE_PRIVATE_KEY: Joi.string().allow('').default(''),
  FIREBASE_CLIENT_EMAIL: Joi.string().allow('').default(''),
  FIREBASE_CLIENT_ID: Joi.string().allow('').default(''),

  // AWS Configuration
  AWS_REGION: Joi.string().default('us-east-1'),
  AWS_ACCESS_KEY_ID: Joi.string().allow('').default(''),
  AWS_SECRET_ACCESS_KEY: Joi.string().allow('').default(''),
  AWS_S3_BUCKET: Joi.string().default('ayaztrade-storage'),
  AWS_S3_REGION: Joi.string().default('us-east-1'),
  AWS_S3_ENDPOINT: Joi.string().allow('').default(''),
  AWS_S3_FORCE_PATH_STYLE: Joi.string().valid('true', 'false').default('false'),
  AWS_SES_REGION: Joi.string().default('us-east-1'),
  AWS_SES_FROM_EMAIL: Joi.string().email().default('noreply@ayaztrade.com'),
  AWS_SNS_REGION: Joi.string().default('us-east-1'),
  AWS_SQS_REGION: Joi.string().default('us-east-1'),
  AWS_SQS_QUEUE_URL: Joi.string().allow('').default(''),

  // Payment Configuration
  STRIPE_SECRET_KEY: Joi.string().allow('').default(''),
  STRIPE_PUBLISHABLE_KEY: Joi.string().allow('').default(''),
  STRIPE_WEBHOOK_SECRET: Joi.string().allow('').default(''),
  STRIPE_CURRENCY: Joi.string().default('usd'),
  IYZICO_API_KEY: Joi.string().allow('').default(''),
  IYZICO_SECRET_KEY: Joi.string().allow('').default(''),
  IYZICO_BASE_URL: Joi.string().uri().default('https://sandbox-api.iyzipay.com'),
  IYZICO_CURRENCY: Joi.string().default('TRY'),
  PAYPAL_CLIENT_ID: Joi.string().allow('').default(''),
  PAYPAL_CLIENT_SECRET: Joi.string().allow('').default(''),
  PAYPAL_MODE: Joi.string().valid('sandbox', 'live').default('sandbox'),
  PAYPAL_CURRENCY: Joi.string().default('USD'),

  // Email Configuration
  SMTP_HOST: Joi.string().default('smtp.gmail.com'),
  SMTP_PORT: Joi.number().default(587),
  SMTP_SECURE: Joi.string().valid('true', 'false').default('false'),
  SMTP_USER: Joi.string().allow('').default(''),
  SMTP_PASS: Joi.string().allow('').default(''),
  SMTP_TLS_REJECT_UNAUTHORIZED: Joi.string().valid('true', 'false').default('false'),
  EMAIL_FROM: Joi.string().email().default('noreply@ayaztrade.com'),
  EMAIL_REPLY_TO: Joi.string().email().default('support@ayaztrade.com'),
  EMAIL_TEMPLATE_DIR: Joi.string().default('./templates/email'),
  SENDGRID_API_KEY: Joi.string().allow('').default(''),
  SENDGRID_FROM_EMAIL: Joi.string().email().default('noreply@ayaztrade.com'),
  SENDGRID_FROM_NAME: Joi.string().default('AyazTrade'),
  MAILGUN_API_KEY: Joi.string().allow('').default(''),
  MAILGUN_DOMAIN: Joi.string().allow('').default(''),
  MAILGUN_FROM_EMAIL: Joi.string().email().default('noreply@ayaztrade.com'),

  // SMS Configuration
  SMS_API_KEY: Joi.string().allow('').default(''),
  SMS_API_URL: Joi.string().uri().default('https://api.netgsm.com.tr'),
  SMS_SENDER: Joi.string().default('AyazTrade'),
  NETGSM_USERNAME: Joi.string().allow('').default(''),
  NETGSM_PASSWORD: Joi.string().allow('').default(''),
  NETGSM_HEADER: Joi.string().allow('').default(''),

  // WhatsApp Configuration
  WHATSAPP_PHONE_NUMBER_ID: Joi.string().allow('').default(''),
  WHATSAPP_ACCESS_TOKEN: Joi.string().allow('').default(''),
  WHATSAPP_VERIFY_TOKEN: Joi.string().allow('').default(''),
  WHATSAPP_WEBHOOK_URL: Joi.string().uri().allow('').default(''),

  // e-Fatura Configuration
  GIB_E_INVOICE_ENABLED: Joi.string().valid('true', 'false').default('false'),
  GIB_E_INVOICE_ENVIRONMENT: Joi.string().valid('sandbox', 'production').default('sandbox'),
  GIB_E_INVOICE_ALIAS: Joi.string().allow('').default(''),
  GIB_E_INVOICE_USERNAME: Joi.string().allow('').default(''),
  GIB_E_INVOICE_PASSWORD: Joi.string().allow('').default(''),
  GIB_E_INVOICE_TEST_MODE: Joi.string().valid('true', 'false').default('true'),

  // Queue Configuration
  QUEUE_REMOVE_ON_COMPLETE: Joi.number().default(10),
  QUEUE_REMOVE_ON_FAIL: Joi.number().default(5),
  QUEUE_ATTEMPTS: Joi.number().default(3),
  QUEUE_BACKOFF_DELAY: Joi.number().default(2000),
  QUEUE_STALLED_INTERVAL: Joi.number().default(30000),
  QUEUE_MAX_STALLED_COUNT: Joi.number().default(1),
  KAFKA_CLIENT_ID: Joi.string().default('ayaztrade'),
  KAFKA_BROKERS: Joi.string().default('localhost:9092'),
  KAFKA_SSL: Joi.string().valid('true', 'false').default('false'),
  KAFKA_SASL_MECHANISM: Joi.string().valid('plain', 'scram-sha-256', 'scram-sha-512').default('plain'),
  KAFKA_SASL_USERNAME: Joi.string().allow('').default(''),
  KAFKA_SASL_PASSWORD: Joi.string().allow('').default(''),
  KAFKA_CONNECTION_TIMEOUT: Joi.number().default(3000),
  KAFKA_REQUEST_TIMEOUT: Joi.number().default(30000),
  KAFKA_INITIAL_RETRY_TIME: Joi.number().default(100),
  KAFKA_RETRIES: Joi.number().default(5),

  // Feature Flags
  SWAGGER_ENABLED: Joi.string().valid('true', 'false').default('true'),
  METRICS_ENABLED: Joi.string().valid('true', 'false').default('true'),
  COMPRESSION_ENABLED: Joi.string().valid('true', 'false').default('true'),
  COMPRESSION_LEVEL: Joi.number().default(6),
  COMPRESSION_THRESHOLD: Joi.number().default(1024),
  REQUEST_TIMEOUT: Joi.number().default(30000),
  RESPONSE_TIMEOUT: Joi.number().default(30000),
  BODY_SIZE_LIMIT: Joi.string().default('10mb'),
  URL_SIZE_LIMIT: Joi.string().default('2kb'),
  PARAMETER_LIMIT: Joi.number().default(1000),
});
